CREATE SCHEMA payroll;

USE payroll;

CREATE TABLE department (
    dp_id INT AUTO_INCREMENT PRIMARY KEY,
    dp_name VARCHAR(45)
);

CREATE TABLE employee (
    em_id INT AUTO_INCREMENT PRIMARY KEY,
    em_name VARCHAR(45),
    em_salary DECIMAL(10,2),
    em_permanent BOOLEAN,
    em_date_of_birth DATE,
    em_dp_id INT,
    FOREIGN KEY (em_dp_id) REFERENCES department(dp_id)
);

CREATE TABLE skill (
    sk_id INT AUTO_INCREMENT PRIMARY KEY,
    sk_name VARCHAR(45)
);

CREATE TABLE employee_skill (
    es_id INT AUTO_INCREMENT PRIMARY KEY,
    es_em_id INT,
    es_sk_id INT,
    FOREIGN KEY (es_em_id) REFERENCES employee(em_id),
    FOREIGN KEY (es_sk_id) REFERENCES skill(sk_id)
);

INSERT INTO department (dp_name) VALUES ('HR');
INSERT INTO department (dp_name) VALUES ('Engineering');
INSERT INTO department (dp_name) VALUES ('Sales');
INSERT INTO department (dp_name) VALUES ('Marketing');
INSERT INTO department (dp_name) VALUES ('Finance');
INSERT INTO department (dp_name) VALUES ('Support');
INSERT INTO skill (sk_name) VALUES ('Java');
INSERT INTO skill (sk_name) VALUES ('Python');
INSERT INTO skill (sk_name) VALUES ('SQL');
INSERT INTO skill (sk_name) VALUES ('C++');
INSERT INTO skill (sk_name) VALUES ('JavaScript');
INSERT INTO skill (sk_name) VALUES ('Spring');
INSERT INTO skill (sk_name) VALUES ('Hibernate');
INSERT INTO skill (sk_name) VALUES ('Docker');
INSERT INTO skill (sk_name) VALUES ('Kubernetes');
INSERT INTO skill (sk_name) VALUES ('AWS');
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_1', 82892.09, 1, '1992-02-15', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_2', 110684.25, 0, '1991-04-04', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_3', 78724.93, 0, '1995-12-15', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_4', 97126.02, 1, '1989-03-28', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_5', 101125.68, 1, '1997-05-24', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_6', 84451.7, 0, '1975-08-03', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_7', 75366.31, 0, '1977-02-27', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_8', 45251.51, 0, '1992-02-27', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_9', 90236.61, 1, '2000-06-14', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_10', 97690.74, 0, '1973-04-21', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_11', 74122.27, 0, '1972-09-13', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_12', 87431.76, 0, '1990-08-27', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_13', 103783.36, 1, '1995-02-28', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_14', 98225.99, 1, '1987-10-02', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_15', 56855.88, 0, '1997-12-08', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_16', 49113.23, 0, '1984-06-18', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_17', 59475.55, 0, '1973-01-22', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_18', 35577.39, 0, '1983-10-28', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_19', 39490.03, 0, '1982-09-07', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_20', 106420.74, 1, '1977-06-12', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_21', 98872.78, 0, '1980-09-21', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_22', 62843.62, 0, '1989-11-01', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_23', 98717.16, 0, '1972-09-17', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_24', 46877.47, 1, '1976-05-01', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_25', 103182.29, 0, '1990-01-22', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_26', 32686.24, 1, '1985-12-16', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_27', 38986.33, 1, '1971-10-15', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_28', 88807.06, 0, '1999-09-14', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_29', 66822.84, 1, '1977-05-12', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_30', 80907.9, 0, '1980-03-16', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_31', 42893.51, 1, '1986-07-25', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_32', 38698.73, 1, '1970-11-03', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_33', 100627.37, 1, '1977-11-09', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_34', 67647.45, 0, '2000-02-15', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_35', 116240.51, 0, '1970-06-08', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_36', 63101.53, 1, '1971-11-21', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_37', 44831.11, 0, '1979-12-18', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_38', 107803.16, 0, '1974-05-17', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_39', 113109.79, 1, '1981-04-14', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_40', 40743.1, 0, '1973-12-22', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_41', 91537.64, 1, '1994-06-12', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_42', 73539.85, 1, '1977-02-18', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_43', 113211.96, 0, '1970-04-25', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_44', 111682.41, 0, '1970-09-30', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_45', 92824.0, 0, '1980-07-11', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_46', 71443.17, 0, '1995-06-21', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_47', 63125.6, 1, '1987-11-04', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_48', 77044.23, 1, '1989-09-19', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_49', 39985.95, 0, '1975-11-24', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_50', 37847.65, 1, '1971-06-14', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_51', 93134.89, 1, '1985-02-03', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_52', 82500.54, 1, '1970-10-15', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_53', 73048.64, 1, '1975-02-13', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_54', 116053.07, 0, '1990-02-17', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_55', 36617.81, 1, '1997-11-21', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_56', 114007.39, 1, '1990-04-03', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_57', 75256.01, 1, '1974-07-18', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_58', 67046.34, 1, '1985-10-30', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_59', 116483.67, 1, '1982-08-21', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_60', 82896.71, 1, '1980-12-13', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_61', 48546.61, 0, '1977-01-09', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_62', 79014.46, 0, '1989-09-12', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_63', 94494.06, 0, '1977-01-18', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_64', 96911.53, 0, '1996-01-29', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_65', 101874.89, 1, '1983-06-16', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_66', 115861.32, 0, '1979-06-20', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_67', 113083.25, 1, '1973-11-01', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_68', 105420.5, 1, '1972-07-18', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_69', 65980.36, 1, '1975-09-17', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_70', 115167.31, 0, '1972-06-23', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_71', 71717.41, 0, '2000-07-15', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_72', 113943.15, 1, '1995-05-12', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_73', 81529.98, 1, '1970-02-10', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_74', 85913.83, 0, '1984-10-06', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_75', 106089.9, 0, '1984-02-20', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_76', 54007.67, 0, '1993-01-01', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_77', 37583.13, 0, '1985-02-03', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_78', 37951.37, 1, '1990-07-07', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_79', 95656.47, 0, '1985-05-22', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_80', 102144.01, 1, '1987-05-25', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_81', 96313.54, 1, '1974-06-27', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_82', 94001.42, 0, '1994-08-04', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_83', 69969.69, 0, '1990-04-21', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_84', 53791.17, 1, '1985-07-08', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_85', 92592.98, 0, '1983-08-08', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_86', 91066.52, 1, '1991-03-31', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_87', 72384.86, 1, '1980-01-15', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_88', 117927.14, 1, '1998-02-25', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_89', 47251.5, 1, '1981-05-01', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_90', 59142.65, 1, '1984-06-30', 1);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_91', 66929.87, 1, '1972-03-30', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_92', 80255.7, 1, '1982-09-30', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_93', 85742.03, 1, '1987-05-28', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_94', 36818.39, 0, '2000-05-13', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_95', 36419.68, 0, '1989-03-27', 6);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_96', 50144.03, 1, '1997-03-26', 4);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_97', 69233.06, 1, '1980-02-25', 5);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_98', 51391.63, 1, '1973-09-23', 2);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_99', 100980.13, 1, '1972-12-29', 3);
INSERT INTO employee (em_name, em_salary, em_permanent, em_date_of_birth, em_dp_id) VALUES ('Employee_100', 68134.54, 1, '1982-11-18', 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (1, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (1, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (1, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (2, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (3, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (3, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (3, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (4, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (4, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (4, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (5, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (5, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (6, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (6, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (7, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (7, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (7, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (8, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (8, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (8, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (9, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (9, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (10, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (11, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (12, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (12, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (12, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (13, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (13, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (14, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (14, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (14, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (15, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (15, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (15, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (16, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (17, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (18, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (18, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (18, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (19, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (19, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (19, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (20, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (20, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (20, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (21, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (21, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (21, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (22, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (22, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (23, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (23, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (23, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (24, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (25, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (25, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (25, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (26, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (26, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (26, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (27, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (27, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (28, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (28, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (28, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (29, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (29, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (29, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (30, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (30, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (31, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (31, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (32, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (32, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (33, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (33, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (33, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (34, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (34, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (34, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (35, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (36, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (37, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (37, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (38, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (38, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (39, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (39, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (40, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (40, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (40, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (41, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (41, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (41, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (42, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (42, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (43, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (43, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (43, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (44, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (45, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (46, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (46, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (47, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (47, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (48, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (48, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (49, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (50, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (51, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (52, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (53, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (54, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (55, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (55, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (55, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (56, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (56, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (56, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (57, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (57, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (57, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (58, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (59, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (59, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (60, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (61, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (62, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (62, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (62, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (63, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (63, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (64, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (64, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (64, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (65, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (66, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (66, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (66, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (67, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (67, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (67, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (68, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (69, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (69, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (70, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (71, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (71, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (72, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (72, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (73, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (73, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (74, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (75, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (76, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (77, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (77, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (78, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (78, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (78, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (79, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (79, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (79, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (80, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (80, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (80, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (81, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (81, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (82, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (82, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (83, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (83, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (84, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (85, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (85, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (85, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (86, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (86, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (86, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (87, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (87, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (87, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (88, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (89, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (89, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (90, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (91, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (91, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (92, 4);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (92, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (93, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (93, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (93, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (94, 8);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (95, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (95, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (95, 6);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (96, 2);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (96, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (96, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (97, 9);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (97, 7);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (97, 3);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (98, 5);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (99, 10);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (100, 1);
INSERT INTO employee_skill (es_em_id, es_sk_id) VALUES (100, 6);


SELECT * FROM department;
SELECT * FROM employee;
SELECT * FROM employee_skill;
SELECT * FROM skill;